# Generated by Django 5.1.4 on 2025-01-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_head', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('remark_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'remarks',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('default_tax', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tax',
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('financial_year_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='bms_app.company')),
            ],
            options={
                'db_table': 'financial_year',
            },
        ),
        migrations.CreateModel(
            name='GSTDetails',
            fields=[
                ('gst_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='bms_app.company')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='bms_app.financialyear')),
            ],
            options={
                'db_table': 'gst_details',
            },
        ),
        migrations.CreateModel(
            name='CompanyPartyInvoiceDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_invoice_details', to='bms_app.company')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_invoice_details', to='bms_app.financialyear')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_invoice_details', to='bms_app.party')),
            ],
            options={
                'db_table': 'company_party_invoice_details',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('party_bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brokerage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brokerage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brokerage_gst', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bms_app.company')),
                ('company_financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bms_app.financialyear')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_party', to='bms_app.party')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bms_app.items')),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bms_app.remarks')),
                ('seller_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_seller_party', to='bms_app.party')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bms_app.tax')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
